export const MOVIE_GENRES_ICON: { [key: string]: string } = {
  'триллер': '/images/thriller.png',
  'военный': '/images/war.png',
  'боевик': '/images/action.png',
  'спорт': '/images/sport.png',
  'музыка': '/images/music.png',
  'приключения': '/images/adventures.png',
  'короткометражка': '/images/short.png',
  'аниме': '/images/anime.png',
  'детектив': '/images/detective.png',
  'мюзикл': '/images/musical.png',
  'детский': '/images/kids.png',
  'история': '/images/history.png',
  'биография': '/images/biography.png',
  'ток-шоу': '/images/talkshow.png',
  'фильм-нуар': '/images/noir.png',
  'мелодрама': '/images/melodrama.png',
  'мультфильм': '/images/cartoon.png',
  'концерт': '/images/concert.png',
  'драма': '/images/drama.png',
  'вестерн': '/images/western.png',
  'семейный': '/images/family.png',
  'фэнтези': '/images/fantasy.png',
  'ужасы': '/images/horror.png',
  'комедия': '/images/comedy.png',
  'фантастика': '/images/fantastic.png',
  'реальное ТВ': '/images/realtv.png',
  'криминал': '/images/criminal.png',
  'документальный': '/images/documentary.png',
};
